version: '3.8'

services:
  restaurant.web:
    container_name: mtogo-restaurant-web
    image: mtogo.restaurant.web
    build:
      context: .
      dockerfile: src/Restaurant.Web/Dockerfile
    ports:
      - "8081:80"
    networks:
      - kafka

  restaurant.grpc:
    container_name: mtogo-restaurant-grpc
    image: mtogo.restaurant.grpc
    build:
      context: .
      dockerfile: src/Restaurant.Grpc/Dockerfile
    ports:
      - "8000:8000"
    networks:
      - kafka

networks:
  kafka:
    external: true
