name: CI

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '7.0.306'

    - name: Restore dependencies
      run: dotnet restore test/Auth.Test

    - name: Run tests
      run: dotnet test --configuration Release test/Auth.Test

    - name: Build and run Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d --build
